### ISSUE TITLE
Join Button doesn't work as expected

### ISSUE THREAD

**Issue by MarcBollmann** [BuchholzTim/Whitebird#13]
### Describe your Issue
When on the main page when clicking on join and entering the join code nothing happens.

### How to reproduce?
Go to the main page click on _Join_ and enter the corresponding Join-Code.

### What would be the expected behavior?
You will get redirected to http://ipadress:port/Whiteboard and join the room via sockets.

**Comment by BuchholzTim** [comment]
Fixed in 8bfc63bd0edd8474cf41490040517fa2e1b2a06c
