### ISSUE TITLE
Mini UI Fixes

### ISSUE THREAD

**Issue by BuchholzTim** [BuchholzTim/Whitebird#23]
### Describe your Issue
Serveral minimal issues in the UI

![grafik](https://user-images.githubusercontent.com/25686940/105163731-93ad1700-5b14-11eb-94ad-9c3d3c8a1329.png)

These buttons do not link to anywhere.

--------------------
![grafik](https://user-images.githubusercontent.com/25686940/105163809-aaec0480-5b14-11eb-97a7-0c289c21fda8.png)

These links still link to `/MTI-Projekt` instead of `/Whitebird`

--------------------
![grafik](https://user-images.githubusercontent.com/25686940/105163904-c1925b80-5b14-11eb-9174-129b0592b320.png)

No links at all

--------------------
![grafik](https://user-images.githubusercontent.com/25686940/105163941-cd7e1d80-5b14-11eb-994d-e2b9c229788c.png)

Logo still wrong

--------------------
![grafik](https://user-images.githubusercontent.com/25686940/105164029-e686ce80-5b14-11eb-8e4a-ef1f40e7e892.png)

Should be the White-Bird

**Comment by BeckmannArmin** [comment]
Propose another logo
