### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by BuchholzTim** [BuchholzTim/Whitebird#26]
### Describe your Issue
A Documentation in the Wiki should be provided to illustrate to Key-Features and at least a How-To and Get-Started

**Comment by MarcBollmann** [comment]
Updated Wiki Home https://github.com/BuchholzTim/Whitebird/wiki

**Comment by MarcBollmann** [comment]
- Updated https://github.com/BuchholzTim/Whitebird/wiki/Getting-Started-Dev
- Updated https://github.com/BuchholzTim/Whitebird/wiki/Getting-Started
- Updated https://github.com/BuchholzTim/Whitebird/wiki/Known-problems

**Comment by MarcBollmann** [comment]
Added architecture https://github.com/BuchholzTim/Whitebird/wiki/Architecture
