### ISSUE TITLE
Invite Button / Modal

### ISSUE THREAD

**Issue by BuchholzTim** [BuchholzTim/Whitebird#27]
### Describe your Issue
![grafik](https://user-images.githubusercontent.com/25686940/105205951-17cbc280-5b46-11eb-85cf-e2a66fe96dd6.png)

This Button currently only responds to the second click.

![grafik](https://user-images.githubusercontent.com/25686940/105206039-2e721980-5b46-11eb-8deb-543a9efcd0ee.png)

And the Modal does not close, when clicked on the 'x' in the upper right corner.

**Comment by BeckmannArmin** [comment]
Pull the latest changes
