### ISSUE TITLE
Rotating notes inconsistent behavior

### ISSUE THREAD

**Issue by MarcBollmann** [BuchholzTim/Whitebird#28]
### Describe your Issue
When rotating a note. The synced object on the other clients doesn't work as intended.

### How to reproduce?
- Create a note
- rotate it
- switch to the other client
- 1. Issue: the note is not editable only when you use the selector see #14 
![image](https://user-images.githubusercontent.com/25687814/105210854-e229d800-5b4b-11eb-9939-d95aeb19995f.png)
![image](https://user-images.githubusercontent.com/25687814/105210948-fd94e300-5b4b-11eb-9704-34840a90ad2c.png)
- 2. Issue: 
the rebuilt note on the other client can be distorted
![image](https://user-images.githubusercontent.com/25687814/105211470-93c90900-5b4c-11eb-88cc-f54fc61ee579.png)

### What would be the expected behavior?
The note should be editable and should behave exactly like on the source client.

**Comment by GeiserRafael** [comment]
The Stickynote did not have its normal settings, so these still had to be added
