### ISSUE TITLE
Customizable Text

### ISSUE THREAD

**Issue by BuchholzTim** [BuchholzTim/Whitebird#38]
### Describe your Issue
Text-Tool and StickyNote-Tool should provide an Option to change its desing.

- Font Size
- Font Type
- Font Color?

**Comment by MarcBollmann** [comment]
Modal needed for font size, font type, font color @BeckmannArmin

**Comment by MarcBollmann** [comment]
Fonts loading in fabric @MarcBollmann

**Comment by MarcBollmann** [comment]
Armin hat das Font Loading schon erledigt!

**Comment by MarcBollmann** [comment]
- Font-Text sizes automatically with the text length
- Fonts are changeable
- Font-Style is changeable
