### ISSUE TITLE
Promote whitebird on external sites

### ISSUE THREAD

**Issue by MarcBollmann** [BuchholzTim/Whitebird#45]
### Describe your Issue
When the first milestone is reached we should contribute our project on some developer communities.

ideas:
- https://devpost.com/software/built-with/fabric-js
- https://www.reddit.com/r/selfhosted/
- https://github.com/awesome-selfhosted/awesome-selfhosted
- https://www.producthunt.com/

**Comment by GeiserRafael** [comment]
https://devpost.com/software/built-with/fabric-js

**Comment by MarcBollmann** [comment]
https://devpost.com/software/whitebird-open-source-collaborative-digital-whiteboard

**Comment by MarcBollmann** [comment]
https://www.reddit.com/r/selfhosted/comments/lnddc7/whitebird_a_opensource_webbased_collaborative/

**Comment by MarcBollmann** [comment]
https://www.producthunt.com/posts/whitebird
