### ISSUE TITLE
Host Demo

### ISSUE THREAD

**Issue by MarcBollmann** [BuchholzTim/Whitebird#47]
### Tell us about your client:
- Browser:
- Browser-Version:
- OS:
- etc.

**Comment by BuchholzTim** [comment]
Deploying on Heroku might not be possible for free since we need a MongoDB, which would be provided by https://elements.heroku.com/addons/ormongo , which is not free afaik.

**Comment by BuchholzTim** [comment]
Backend Hosted

**Comment by BuchholzTim** [comment]
https://whitebird-demo.herokuapp.com Hosted
