### ISSUE TITLE
Backend-Tasks

### ISSUE THREAD

**Issue by BuchholzTim** [BuchholzTim/Whitebird#5]
### Describe your Issue

- [x] Rooms vs. Namespaces (Namespaces are called `channel` in nuxt-socket-io)
- [x] Correct Implementation of Socket-Events for emitting changes on canvas to Client (see nuxt.config.js)
- [x] `mtiID`-Validation should now validate custom JSON-Property `mtiData`

**Comment by MarcBollmann** [comment]
es wurde weiterhin nun mit rooms gearbeitet
