### ISSUE TITLE
StickyNote Font Size rverting in Edit-Mode

### ISSUE THREAD

**Issue by BuchholzTim** [BuchholzTim/Whitebird#54]
### Describe your Issue
If the Font size is kinda big after resizing the Note, it gets small again when entering the Edit-Mode

https://user-images.githubusercontent.com/25686940/107018337-98bec700-67a0-11eb-9f67-c8f418d9a405.mp4

**Comment by GeiserRafael** [comment]
Fixed with new StickyNote commit: 032622cd53306ec030fc057187d1501bce94d784
