### ISSUE TITLE
Drag & Drop Images

### ISSUE THREAD

**Issue by BuchholzTim** [BuchholzTim/Whitebird#55]
### Describe your Issue
It should be possible to just dragn'n'drop images into the canvas.

Code demo looks like this: https://codepen.io/dizzyluo/pen/LZbzYv

**Comment by MarcBollmann** [comment]
At the moment svg's are are still buggy and it seems that the svg behavior changes on different browsers. See https://github.com/fabricjs/fabric.js/issues/5512

**Comment by MarcBollmann** [comment]
a9cf10ef537224285119a547444f5cd060f18640

**Comment by MarcBollmann** [comment]
With the method `loadSVGFromString()` it works.

**Comment by MarcBollmann** [comment]
solved with 3d027ff10a59ef3a335861d21828cb867f66f065
