### ISSUE TITLE
Alert messages with proper styling

### ISSUE THREAD

**Issue by BeckmannArmin** [BuchholzTim/Whitebird#58]
### Describe your Issue
When the user drag and drop an unsupported file type into the canvas the standard alert - without any stlying - pops up.

### How to reproduce?
Drag & Drop something different than svg, jpeg/jpg or png on the canvas

### What would be the expected behavior?
Better looking alert

### Tell us about your client:
- Browser: Chrome, IE, Firefox
- Browser-Version: latest
- OS: Win10
- etc.

**Comment by BuchholzTim** [comment]
Closed in 39189a5f53ea0e087c75d08cf5c966645d3a30c4
