### ISSUE TITLE
Unable to make a PR

### ISSUE THREAD

**Issue by tripathi-abhishek** [BuchholzTim/Whitebird#80]
### Describe your Issue
Was trying out your project and I saw a simple spelling mistake. I thought of making a PR but git says permission denied.
SPELLING OF WAITING WAS WRONG(wating) + SPELLING OF ISSUING WAS WRONG(issueing)
![2021-04-09_150909](https://user-images.githubusercontent.com/43468297/114161998-4c316c80-9946-11eb-969b-393acc039f3d.jpg)

`remote: Permission to BuchholzTim/Whitebird.git denied to tr-abhishek.`

### How to reproduce?
Just make a branch, add your changes, commit and push.

### What would be the expected behavior?
I thought the project is open-source, so I should be able to make PRs and such.

### Tell us about your client:
- Browser: Firefox
- Browser-Version: 87.0 (64-bit)
- OS: Linux
- etc.

**Comment by TheTechRobo** [comment]
you have to make a FORK on github, you cant directly push to the repo
